// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXvU3vMYhUmur-KHjxkKhABsiOzM5mELI',
    appId: '1:819103392540:web:479421eaf2c9bb79c190d9',
    messagingSenderId: '819103392540',
    projectId: 'dayle-database',
    authDomain: 'dayle-database.firebaseapp.com',
    storageBucket: 'dayle-database.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5AZ9ydhI2hnDVdf1VDB6rbZzusHAnzr0',
    appId: '1:819103392540:android:f1e396293ccf892dc190d9',
    messagingSenderId: '819103392540',
    projectId: 'dayle-database',
    storageBucket: 'dayle-database.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA152ZgSTiZI71o0IZhRjcpQ938xYArDr8',
    appId: '1:819103392540:ios:5450d4d05b215261c190d9',
    messagingSenderId: '819103392540',
    projectId: 'dayle-database',
    storageBucket: 'dayle-database.firebasestorage.app',
    iosClientId:
        '819103392540-bq1hfpockt7kvt7qi4bigk5og48p7t91.apps.googleusercontent.com',
    iosBundleId: 'com.example.dayle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA152ZgSTiZI71o0IZhRjcpQ938xYArDr8',
    appId: '1:819103392540:ios:5450d4d05b215261c190d9',
    messagingSenderId: '819103392540',
    projectId: 'dayle-database',
    storageBucket: 'dayle-database.firebasestorage.app',
    iosClientId:
        '819103392540-bq1hfpockt7kvt7qi4bigk5og48p7t91.apps.googleusercontent.com',
    iosBundleId: 'com.example.dayle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXvU3vMYhUmur-KHjxkKhABsiOzM5mELI',
    appId: '1:819103392540:web:fd850e9794c26392c190d9',
    messagingSenderId: '819103392540',
    projectId: 'dayle-database',
    authDomain: 'dayle-database.firebaseapp.com',
    storageBucket: 'dayle-database.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDXvU3vMYhUmur-KHjxkKhABsiOzM5mELI',
    appId: '1:819103392540:web:fd850e9794c26392c190d9',
    messagingSenderId: '819103392540',
    projectId: 'dayle-database',
    storageBucket: 'dayle-database.firebasestorage.app',
  );
}
